---

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --args=--hide modules
